# Generated by Django 4.0.5 on 2022-06-26 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='createlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=12)),
                ('assignment_name', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=50)),
                ('start', models.DateTimeField()),
                ('no_of_submissions', models.IntegerField()),
                ('perc_penalty', models.IntegerField()),
                ('first_sub_time', models.DateTimeField()),
                ('second_sub_time', models.DateTimeField()),
                ('notif', models.CharField(max_length=12)),
                ('neg_mark', models.CharField(max_length=12)),
                ('face_rec', models.CharField(max_length=12)),
                ('res_anno', models.CharField(max_length=100)),
                ('result_time', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
