# Generated by Django 4.0.5 on 2022-06-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_1', models.CharField(max_length=500)),
                ('inst_2', models.CharField(max_length=500)),
                ('inst_3', models.CharField(max_length=500)),
                ('inst_4', models.CharField(max_length=500)),
                ('inst_5', models.CharField(max_length=500)),
            ],
        ),
    ]
