# Generated by Django 4.0.5 on 2022-07-03 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAssignment', '0002_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(blank=True, max_length=500)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CreateAssignment.createlink')),
            ],
        ),
        migrations.DeleteModel(
            name='Instructions',
        ),
    ]
